# .github.workflows/google-app-engine-deploy.yaml

name: Deploy to Google App Engine

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
        with:
          credentials: ${{ secret.gcp_credentials }}
