# .github.workflows/google-app-engine-deploy.yaml

name: Deploy to Google App Engine

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check project setting
        run: |
          echo 'GCP_PROJECT: ${{ secrets.GCP_PROJECT }}'
          echo 'GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}'
          echo 'GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}'
      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          promote: false
          version: v1

